### ISSUE TITLE
haven't found any documentation for the new Transformer syntax

### ISSUE THREAD

**Issue by mjdavidson** [adaltas/node-stream-transform#25]
can you please point me in the right direction

**Comment by wdavidw** [comment]
Not sure what you mean, there hasn't been a change in this package for months if not year, the only recent changes introduced by version 2 is how internal state variable are now in a state object as documentated on the [state page](https://csv.js.org/transform/state/). Please comment if you need complementary help, closing for now.

**Comment by mjdavidson** [comment]
sorry i made a mistake!
