### ISSUE TITLE
Request. Update Typescript signature for Handler

### ISSUE THREAD

**Issue by jasonterando** [adaltas/node-stream-transform#28]
Not an urgent thing, but you might want to update the Typescript signature for Handler to include support for params (if specified in options)

Namely, in lib/index.d.ts (and lib/es5/index.d.ts), update

````
type Handler = (record: Array<any>, callback: HandlerCallback) => any
````

to something like...

````
type Handler = (record: Array<any>, callback: HandlerCallback, params?: any) => any
````

**Comment by wdavidw** [comment]
Thank you
