### ISSUE TITLE
Problem with object as input

### ISSUE THREAD

**Issue by pensierinmusica** [adaltas/node-stream-transform#5]
Hi,

I can't figure out how to make this module work with an object as input. According to the documentation it should "Accept object, array or JSON as input and output".

Let's take this simple code:

```
csv.transform(input, function (data) {
  console.log("Progress");
  console.log(data);
  return data;
}, function (err, output) {
  console.log('Done!');
  console.log(output);
});
```

When

`var input = [[1,2,3], ['a','b','c']];`

The console prints:

```
Progress
[ 1, 2, 3 ]
Progress
[ 'a', 'b', 'c' ]
Done!
[ [ 1, 2, 3 ], [ 'a', 'b', 'c' ] ]
```

Which seems perfectly fine. Unfortunately though when

```
var input = {
  foo: {
    number: 1,
    color: 'red',
    desc: 'foo'
  },
  bar: {
    number: 2,
    color: 'blue',
    desc: 'bar'
  },
};
```

The console prints:

```
Done!
[]
```

It looks like the function is not accepting an object as input. Any idea why?

Thanks!

**Comment by pensierinmusica** [comment]
Ok @wdavidw, thanks for the clarification. Should I generate a PR to make docs a bit more clear on this point? Cheers

**Comment by wdavidw** [comment]
yes please, i'll apply it
